version: "3"
services:
  app:
    build:
      context: .
    # ーーーーーローカルと本番で切り替える部分ーーーーー
    # command: bundle exec puma -C config/puma.rb #ローカル環境
    command: bundle exec puma -C config/puma.rb -e production #本番環境
    # ーーーーーローカルと本番で切り替える部分ーーーーー
    volumes:
      - .:/posuke
      - public-data:/posuke/public
      - tmp-data:/posuke/tmp
      - log-data:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
    networks:
      - posuke-network
    stdin_open: true
    tty: true
    # ーーーーーローカルと本番で切り替える部分ーーーーー
  #   depends_on:
  #     - db

  # db:
  #   image: mysql@sha256:dce31fcdd15aaedb5591aa89f19ec37cb79981af46511781fa41287d88ed0abd
  #   volumes:
  #     - db-volume:/var/lib/mysql
  #     - ./mysql-confd:/etc/mysql/conf.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   networks:
  #     - posuke-network
    # ーーーーーローカルと本番で切り替える部分ーーーーー

  web:
    build:
      context: ./containers/nginx
    volumes:
      - public-data:/posuke/public
      - tmp-data:/posuke/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - posuke-network

volumes:
  db-volume:
  public-data:
  tmp-data:
  log-data:

networks:
  posuke-network:
    external: true
